import Config from 'react-native-config';

interface ApiEndpoints {
  [key: string]: string;
}

const API_URL = Config.BASE_URL + '/api/';

export const API: ApiEndpoints = {
  _getSidebarRecord: `${API_URL}sidebar`,
  _getDashboardRecord: `${API_URL}dashboard`,
  _login: `${API_URL}login`,
  _changePassword: `${API_URL}change-password`,
  _sendOtp: `${API_URL}send-otp`,
  _verifyOtp: `${API_URL}verify-otp`,
  _resetPassword: `${API_URL}reset-password`,
  _logoutAll: `${API_URL}logout-all`,
  _logout: `${API_URL}logout`,
  _getProfile: `${API_URL}get-profile`,
  _updateUserProfile: `${API_URL}update-profile`,
  _uploadFile: `${API_URL}upload-file`,
  _mediaConvert: `${API_URL}media-convert`,
  _addContact: `${API_URL}contact`,
  _getContactDetail: `${API_URL}contact/`,
  _deleteContact: `${API_URL}contact/`,
  _getContacts: `${API_URL}contact`,
  _getAllContacts: `${API_URL}list/contact-number`,
  _getContactDetailType: `${API_URL}list/contact-detail-type`,
  _getCountryDetails: `${API_URL}list/countries-state`,
  _getCallLogs: `${API_URL}call-log`,
  _getGroup: `${API_URL}group/`,
  _updateGroup: `${API_URL}group/`,
  _changeGroupStatus: `change-status`,
  _getEmployeeList: `${API_URL}list/employee/`,
  _getCommNumber: `${API_URL}list/communication-number/`,
  _getTag: `${API_URL}tag/`,
  _updateTag: `${API_URL}tag/`,
  _getTagType: `${API_URL}list/tag-type`,
  _getListGroup: `${API_URL}list/group/`,
  _getBusinessSmsThread: `${API_URL}business-sms/thread`,
  _getBusinessSmsThreadMessage: `${API_URL}business-sms/thread-message/`,
  _getBusinessSmsThreadAction: `${API_URL}business-sms/thread-action/`,
  _getWhatsappThread: `${API_URL}whatsapp/thread`,
  _getWhatsappThreadMessage: `${API_URL}whatsapp/thread-message/`,
  _getWhatsappThreadAction: `${API_URL}whatsapp/thread-action/`,
  _getGroupDetail: `${API_URL}list/group-detail/`,
  _crudRolePermission: `${API_URL}role-and-permission`,
  _crudEmployee: `${API_URL}employee`,
  _getRolesHierarchy: `${API_URL}role-and-permission/hierarchy`,
  _crudQuickReplies: `${API_URL}quick-reply`,
  _changeQuickReplyStatus: `change-status`,
  _getAllGroups: `${API_URL}list/all-group`,
  _getWhatsappNumber: `${API_URL}whatsapp-number`,
  _getWhatsappTemplate: `${API_URL}whatsapp-template`,
  _getWhatsappTemplateById: `${API_URL}list/whatsapp-template`,
  _changeWhatsappTemplateStatus: `change-status`,
  _getTeamChatThread: `${API_URL}team-chat/thread`,
  _getTeamChatThreadMessage: `${API_URL}team-chat/thread-message/`,
  _crudTeamChatUpdateGroup: `${API_URL}team-chat/group`,
  _teamChatGetMessageStatus: `${API_URL}team-chat/message-info`,
  _getWebChat: `${API_URL}web-chat/`,
  _webChatTransfer: `transfer/`,
  _webChatCloseSession: `/session-close/`,
  _getWebChatThread: `/thread`,
  _getWebChatThreadMessage: `/thread-message/`,
  _crudWebChatUpdateGroup: `/group`,
  _crudWidget: `${API_URL}widget`,
  _crudForm: `${API_URL}form`,
  _getForms: `${API_URL}list/forms`,
  _crudVisitorRequest: `${API_URL}visitor/requests`,
  _transferRequest: `${API_URL}visitor/transfer/`,
  _getVisitorDetail: `/visitor/`,
  _getWebChatSessions: `/sessions`,
  _requestChangeStatus: `/change-status`,
  _changeStatus: `/change-status`,
  _crudFeedback: `${API_URL}feedback`,
  _crudComment: `${API_URL}comment`,
  _getNotificationSettingHierarchy: `${API_URL}notification-permission/hierarchy`,
  _submitNotificationPermission: `${API_URL}notification-permission`,
  _getInAppNotificationsList: `${API_URL}notification`,
  _readInAppNotifications: `read`,
  _location: `${API_URL}shared-location`,
  _locationList: `${API_URL}list/shared-location`,
  _locationStatusUpdate: `/change-status`,

  // push notification
  _push_notification_login: 'customapi/register',
  _push_notification_logout: 'customapi/unregister',
};
