export enum StatusCodes {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLY_HINTS = 103,

  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207,

  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  MOVED_TEMPORARILY = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  REQUEST_TOO_LONG = 413,
  REQUEST_URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  IM_A_TEAPOT = 418,
  INSUFFICIENT_SPACE_ON_RESOURCE = 419,
  METHOD_FAILURE = 420,
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422,
  LOCKED = 423,
  FAILED_DEPENDENCY = 424,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,

  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  INSUFFICIENT_STORAGE = 507,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
}

export const ReasonPhrases: Record<StatusCodes, string> = {
  [StatusCodes.CONTINUE]: 'Continue',
  [StatusCodes.SWITCHING_PROTOCOLS]: 'Switching Protocols',
  [StatusCodes.PROCESSING]: 'Processing',
  [StatusCodes.EARLY_HINTS]: 'Early Hints',

  [StatusCodes.OK]: 'OK',
  [StatusCodes.CREATED]: 'Created',
  [StatusCodes.ACCEPTED]: 'Accepted',
  [StatusCodes.NON_AUTHORITATIVE_INFORMATION]: 'Non Authoritative Information',
  [StatusCodes.NO_CONTENT]: 'No Content',
  [StatusCodes.RESET_CONTENT]: 'Reset Content',
  [StatusCodes.PARTIAL_CONTENT]: 'Partial Content',
  [StatusCodes.MULTI_STATUS]: 'Multi-Status',

  [StatusCodes.MULTIPLE_CHOICES]: 'Multiple Choices',
  [StatusCodes.MOVED_PERMANENTLY]: 'Moved Permanently',
  [StatusCodes.MOVED_TEMPORARILY]: 'Moved Temporarily',
  [StatusCodes.SEE_OTHER]: 'See Other',
  [StatusCodes.NOT_MODIFIED]: 'Not Modified',
  [StatusCodes.USE_PROXY]: 'Use Proxy',
  [StatusCodes.TEMPORARY_REDIRECT]: 'Temporary Redirect',
  [StatusCodes.PERMANENT_REDIRECT]: 'Permanent Redirect',

  [StatusCodes.BAD_REQUEST]: 'Bad Request',
  [StatusCodes.UNAUTHORIZED]: 'Unauthorized',
  [StatusCodes.PAYMENT_REQUIRED]: 'Payment Required',
  [StatusCodes.FORBIDDEN]: 'Forbidden',
  [StatusCodes.NOT_FOUND]: 'Not Found',
  [StatusCodes.METHOD_NOT_ALLOWED]: 'Method Not Allowed',
  [StatusCodes.NOT_ACCEPTABLE]: 'Not Acceptable',
  [StatusCodes.PROXY_AUTHENTICATION_REQUIRED]: 'Proxy Authentication Required',
  [StatusCodes.REQUEST_TIMEOUT]: 'Request Timeout',
  [StatusCodes.CONFLICT]: 'Conflict',
  [StatusCodes.GONE]: 'Gone',
  [StatusCodes.LENGTH_REQUIRED]: 'Length Required',
  [StatusCodes.PRECONDITION_FAILED]: 'Precondition Failed',
  [StatusCodes.REQUEST_TOO_LONG]: 'Request Entity Too Large',
  [StatusCodes.REQUEST_URI_TOO_LONG]: 'Request-URI Too Long',
  [StatusCodes.UNSUPPORTED_MEDIA_TYPE]: 'Unsupported Media Type',
  [StatusCodes.REQUESTED_RANGE_NOT_SATISFIABLE]:
    'Requested Range Not Satisfiable',
  [StatusCodes.EXPECTATION_FAILED]: 'Expectation Failed',
  [StatusCodes.IM_A_TEAPOT]: "I'm a teapot",
  [StatusCodes.INSUFFICIENT_SPACE_ON_RESOURCE]:
    'Insufficient Space on Resource',
  [StatusCodes.METHOD_FAILURE]: 'Method Failure',
  [StatusCodes.MISDIRECTED_REQUEST]: 'Misdirected Request',
  [StatusCodes.UNPROCESSABLE_ENTITY]: 'Unprocessable Entity',
  [StatusCodes.LOCKED]: 'Locked',
  [StatusCodes.FAILED_DEPENDENCY]: 'Failed Dependency',
  [StatusCodes.UPGRADE_REQUIRED]: 'Upgrade Required',
  [StatusCodes.PRECONDITION_REQUIRED]: 'Precondition Required',
  [StatusCodes.TOO_MANY_REQUESTS]: 'Too Many Requests',
  [StatusCodes.REQUEST_HEADER_FIELDS_TOO_LARGE]:
    'Request Header Fields Too Large',
  [StatusCodes.UNAVAILABLE_FOR_LEGAL_REASONS]: 'Unavailable For Legal Reasons',

  [StatusCodes.INTERNAL_SERVER_ERROR]: 'Internal Server Error',
  [StatusCodes.NOT_IMPLEMENTED]: 'Not Implemented',
  [StatusCodes.BAD_GATEWAY]: 'Bad Gateway',
  [StatusCodes.SERVICE_UNAVAILABLE]: 'Service Unavailable',
  [StatusCodes.GATEWAY_TIMEOUT]: 'Gateway Timeout',
  [StatusCodes.HTTP_VERSION_NOT_SUPPORTED]: 'HTTP Version Not Supported',
  [StatusCodes.INSUFFICIENT_STORAGE]: 'Insufficient Storage',
  [StatusCodes.NETWORK_AUTHENTICATION_REQUIRED]:
    'Network Authentication Required',
};

export function getReasonPhrase(code: StatusCodes): string {
  return ReasonPhrases[code] || 'Unknown Status';
}

export function getStatusCode(phrase: string): StatusCodes | undefined {
  const entry = Object.entries(ReasonPhrases).find(
    ([, value]) => value.toLowerCase() === phrase.toLowerCase(),
  );
  return entry ? (Number(entry[0]) as StatusCodes) : undefined;
}
