import { StatusBarProps } from 'react-native';

export interface ThemeColors {
  primary: string;
  background: string;
  drawer_background: string;
  tab_icon: string;
  tab_icon_focus: string;
  tab_background: string;
  tab_border_color: string;
  tab_border_focus_color: string;
  green: string;
  light_green: string;
  dark_green: string;
  black: string;
  transparent: string;
  transparent1: string;
  transparent2: string;
  transparent3: string;
  transparent4: string;
  transparent5: string;
  transparent6: string;
  transparent7: string;
  transparent8: string;
  transparent9: string;
  light_gray: string;
  gray: string;
  dark_gray: string;
  blue: string;
  dark_blue: string;
  light_blue: string;
  blue_border: string;
  red: string;
  dark_red: string;
  light_red: string;
  dark_yellow: string;
  light_yellow: string;
  orange: string;
  text: string;
  light_text: string;
  card?: string;
  white?: string;
  input_background?: string;
  border_color?: string;
  btn_background?: string;
  btn_color?: string;
  btn_border_color?: string;
  label_text?: string;
  input_text?: string;
  cursor_color?: string;
  placeholder_text?: string;
  login_background?: string;
  login_card?: string;
  forgot_text?: string;
  sub_title?: string;
  status_bar_style?: StatusBarProps['barStyle'];
  item_background?: string;
  item_border_color?: string;
  top_tab_background: string;
  top_tab_focus_background?: string;
  top_tab_color?: string;
  top_tab_focus_color?: string;
  icon_color: string;
  light_icon_color: string;
  sender_message_background?: string;
  receiver_message_background?: string;
  sender_border?: string;
  avatar_background?: string;
  avatar_color?: string;
  badge_background?: string;
  modal_background?: string;
  header_icon_color?: string;
  active_color?: string;
  inactive_color?: string;
  active_icon_color?: string;
  inactive_icon_color?: string;
  status_bar_background?: string;
  skeleton_background?: string;
  skeleton_foreground?: string;
  divider_color?: string;
  loader_background?: string;
  loader_color?: string;
  call_btn_background?: string;
  list_background?: string;
  send_btn?: string;
  dropdown_item_background?: string;
  chat_background?: string;
  reply_message?: string;
  media_background?: string;
  sheet_btn_background?: string;
  btn_group_background?: string;
  whatsapp_background?: string;
  menu_background?: string;
  shadow_color?: string;
  action_message_background?: string;
  searchbar_background?: string;
  widget_theme_background?: string;
  choose_file_background?: string;
  display_btn_background?: string;
  table_header_background?: string;
  linkedin_blue?: string;
}

export const lightTheme: ThemeColors = {
  status_bar_style: 'dark-content',
  primary: '#007ac3',
  background: '#fff',
  drawer_background: '#fff',
  tab_icon: '#9DCCF2',
  tab_icon_focus: '#fff',
  tab_background: '#007ac3',
  tab_border_color: '#EDEDED',
  tab_border_focus_color: '#8fc6f4',
  green: '#30BD17',
  light_green: '#CFEBD4',
  dark_green: '#139A2A',
  black: '#000000',
  white: '#fff',
  transparent: 'transparent',
  transparent1: 'rgba(0,0,0,0.1)',
  transparent2: 'rgba(0,0,0,0.2)',
  transparent3: 'rgba(0,0,0,0.3)',
  transparent4: 'rgba(0,0,0,0.4)',
  transparent5: 'rgba(0,0,0,0.5)',
  transparent6: 'rgba(0,0,0,0.6)',
  transparent7: 'rgba(0,0,0,0.7)',
  transparent8: 'rgba(0,0,0,0.8)',
  transparent9: 'rgba(0,0,0,0.9)',
  light_gray: '#F7F7F7',
  gray: '#E7E7E7',
  dark_gray: '#888888',
  blue: '#007ac3',
  dark_blue: '#007ac3',
  light_blue: '#A8D5FD',
  blue_border: '#C5E2FF',
  red: '#ec174e',
  dark_red: '#E20F13',
  light_red: '#eec9d9',
  dark_yellow: '#feab04',
  light_yellow: '#EEE9C9',
  orange: '#f7b11b',
  text: '#222222',
  card: '#007ac3',
  light_text: '#828282',
  border_color: '#E7E7E7',
  btn_background: '#007ac3',
  btn_color: '#fff',
  btn_border_color: '#007ac3',
  label_text: '#828282',
  input_text: '#000',
  cursor_color: '#007ac3',
  placeholder_text: '#828282',
  login_background: '#ebeff4',
  login_card: '#fff',
  forgot_text: '#007ac3',
  sub_title: '#777',
  item_background: '#F7F7F7',
  item_border_color: '#EDEDED',
  top_tab_background: '#F7F7F7',
  top_tab_focus_background: '#A8D5FD',
  top_tab_focus_color: '#007ac3',
  top_tab_color: '#828282',
  icon_color: '#828282',
  light_icon_color: '#bcbcbc',
  sender_message_background: '#d1eaff',
  receiver_message_background: '#eceff3',
  sender_border: '#D2E5F7',
  avatar_background: '#E7E7E7',
  avatar_color: '#828282',
  badge_background: '#E20F13',
  input_background: '#F7F7F7',
  modal_background: '#fff',
  header_icon_color: '#000',
  active_color: '#2C2C2E',
  inactive_color: '#E7E7E7',
  active_icon_color: '#fff',
  inactive_icon_color: '#2C2C2E',
  status_bar_background: '#037d18',
  skeleton_background: '#fff',
  skeleton_foreground: '#D2E5F7',
  divider_color: '#EDEDED',
  loader_background: '#EDEDED',
  loader_color: '#007ac3',
  call_btn_background: '#E7E7E7',
  list_background: '#F7F7F7',
  send_btn: '#007ac3',
  dropdown_item_background: '#F7F7F7',
  chat_background: '#888888',
  reply_message: 'rgba(0,0,0,0.1)',
  media_background: '#fff',
  sheet_btn_background: '#F7F7F7',
  btn_group_background: '#E7E7E7',
  whatsapp_background: '#198754',
  menu_background: '#fff',
  shadow_color: '#47474A',
  action_message_background: '#d1eaff',
  searchbar_background: '#fff',
  widget_theme_background: '#fff',
  choose_file_background: '#E7E7E7',
  display_btn_background: '#fff',
  table_header_background: '#D2E5F7',
  linkedin_blue: '#0A66C2'
};

export const darkTheme: ThemeColors = {
  status_bar_style: 'light-content',
  primary: '#007ac3',
  background: '#15181A',
  drawer_background: '#222224',
  tab_icon: '#B5B5B5',
  tab_icon_focus: '#0692e4',
  tab_background: '#2C2C2E',
  tab_border_color: '#47474A',
  tab_border_focus_color: '#77777a',
  green: '#139A2A',
  light_green: '#1b672380',
  dark_green: '#30BD17',
  light_blue: '#0887d15b',
  black: '#000',
  white: '#fff',
  transparent: 'transparent',
  transparent1: 'rgba(0, 0, 0, 0.1)',
  transparent2: 'rgba(0, 0, 0, 0.2)',
  transparent3: 'rgba(0, 0, 0, 0.3)',
  transparent4: 'rgba(0, 0, 0, 0.4)',
  transparent5: 'rgba(0, 0, 0, 0.5)',
  transparent6: 'rgba(0, 0, 0, 0.6)',
  transparent7: 'rgba(0, 0, 0, 0.7)',
  transparent8: 'rgba(0, 0, 0, 0.8)',
  transparent9: 'rgba(0, 0, 0, 0.9)',
  light_gray: '#2c2c2e',
  gray: '#E7E7E7',
  dark_gray: '#888888',
  blue: '#007ac3',
  dark_blue: '#039ffa',
  blue_border: '#2D4F73',
  red: '#EC174E',
  dark_red: '#FF3B30',
  light_red: '#901b3295',
  dark_yellow: '#feab04',
  light_yellow: '#90801B',
  orange: '#f7b11b',
  text: '#fff',
  light_text: '#BDBDBD',
  card: '#007ac3',
  border_color: '#47474A',
  btn_background: '#47474A',
  btn_color: '#fff',
  btn_border_color: '#47474A',
  label_text: '#fff',
  input_text: '#fff',
  cursor_color: '#fff',
  placeholder_text: '#BDBDBD',
  login_background: '#15181A',
  login_card: '#222224',
  forgot_text: '#fff',
  sub_title: '#BDBDBD',
  item_background: '#222224',
  item_border_color: '#47474A',
  top_tab_background: '#2C2C2E',
  top_tab_focus_background: '#515154',
  top_tab_focus_color: '#fff',
  top_tab_color: '#fff',
  icon_color: '#EFEFEF',
  light_icon_color: '#bcbcbc',
  sender_message_background: '#2C2C2E',
  receiver_message_background: '#47474A',
  sender_border: '#47474A',
  avatar_background: '#B5B5B5',
  avatar_color: '#F7F7F7',
  badge_background: '#E20F13',
  input_background: '#222224',
  modal_background: '#2c2c2e',
  header_icon_color: '#fff',
  active_color: '#EFEFEF',
  inactive_color: '#47474A',
  active_icon_color: '#000',
  inactive_icon_color: '#fff',
  status_bar_background: '#037d18',
  skeleton_background: '#47474A',
  skeleton_foreground: '#515154',
  divider_color: '#44494d',
  loader_background: '#44494d',
  loader_color: '#F7F7F7',
  call_btn_background: '#44494d',
  list_background: '#252527',
  send_btn: '#2C2C2E',
  dropdown_item_background: '#2C2C2E',
  chat_background: '#7793a8',
  reply_message: 'rgba(0,0,0,0.5)',
  media_background: '#44494d',
  sheet_btn_background: '#47474A',
  btn_group_background: '#47474A',
  whatsapp_background: '#198754',
  menu_background: '#47474A',
  shadow_color: '#000',
  action_message_background: '#222224',
  searchbar_background: '#47474A',
  widget_theme_background: '#222224',
  choose_file_background: '#47474A',
  display_btn_background: '#47474A',
  table_header_background: '#222224',
  linkedin_blue: '#0A66C2'
};

export const themes = { light: lightTheme, dark: darkTheme };

export type ThemeMode = keyof typeof themes | 'system';